title: Jin's All
author: Jinsol Kim
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is the great beginning step towards a fantastic software developer. I am nothing, but will be something.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
